spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/libr

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.spring.changelog

logging:
  level:
    ROOT: info
  file:
    name: book_app.log

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
    logfile:
      enabled: true
  health:
    defaults:
      enabled: true