spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/libr

mongock:
  #runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.spring.changelog