spring:
  batch:
    job:
      enabled: false

  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: never
  jpa:
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true

mongock:
  runner-type: InitializingBean
  change-logs-scan-package:
    - ru.otus.spring.changelog